const TestData = [
    {
        mainTitle: '단어시험, Word test',
        subTitle: '1st week',
        dateText: '1st week, Aug 2023',
        quizIdList: [
            'quiz1',
            'quiz2',
            'quiz3',
            'quiz4',
            'quiz5',
            'quiz6',
            'quiz7',
            'quiz8',
            'quiz9',
            'quiz10',
        ],
    },
    {
        mainTitle: '단어시험, Word test',
        subTitle: '2st week',
        dateText: '2st week, Aug 2023',
        quizIdList: [
            'quiz11',
            'quiz12',
            'quiz13',
            'quiz14',
            'quiz15',
            'quiz16',
            'quiz17',
            'quiz18',
            'quiz19',
            'quiz20',
        ],
    },
    {
        mainTitle: '단어시험, Word test',
        subTitle: '3st week',
        dateText: '3st week, Aug 2023',
        quizIdList: [
            'quiz21',
            'quiz22',
            'quiz23',
            'quiz24',
            'quiz25',
            'quiz26',
            'quiz27',
            'quiz28',
            'quiz29',
            'quiz30',
        ],
    },
    {
        mainTitle: '단어시험, Word test',
        subTitle: '4st week',
        dateText: '4st week, Aug 2023',
        quizIdList: [
            'quiz31',
            'quiz32',
            'quiz33',
            'quiz34',
            'quiz35',
            'quiz36',
            'quiz37',
            'quiz38',
            'quiz39',
            'quiz40',
        ],
    },
];

export default TestData;
