/**
 *
 * @type {Array<BadgeObject>}
 */
const badgeList = [
    {
        id: 'QdGBdC049TjTxzz1EYKf',
        title: 'Attend',
        type: 'attend',
        level: 1,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 1,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 1,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 2,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 2,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 2,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 3,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 3,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 3,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 4,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 4,
        // date: new Date(),
        active: true,
    },
    {
        id: 'AIInImgrTirg5OAtf0sX',
        title: 'Test',
        type: 'test',
        level: 4,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 5,
        // date: new Date(),
        active: true,
    },
    {
        id: 'ayvdW3j37hIZjBgJPeYu',
        title: 'Reply',
        type: 'comment',
        level: 5,
        // date: new Date(),
        active: true,
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 5,
        // date: new Date(),
        active: true,
    },
];

export default badgeList;
