/**
 *
 * @type {Array<BadgeObject>}
 */
const badgeList = [
    {
        id: 'QdGBdC049TjTxzz1EYKf',
        title: 'Attend',
        type: 'attend',
        level: 1, // date: new Date(),
        active: false,
        achievement: 1,
        achievementCommentSuffix: 'days',
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 1, // date: new Date(),
        active: false,
        achievement: 5,
        achievementCommentSuffix: 'replies',
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 1, // date: new Date(),
        active: false,
        achievement: 1,
        achievementCommentSuffix: 'tests',
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 2, // date: new Date(),
        active: false,
        achievement: 5,
        achievementCommentSuffix: 'days',
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 2, // date: new Date(),
        active: false,
        achievement: 10,
        achievementCommentSuffix: 'replies',
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 2, // date: new Date(),
        active: false,
        achievement: 3,
        achievementCommentSuffix: 'tests',
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 3, // date: new Date(),
        active: false,
        achievement: 10,
        achievementCommentSuffix: 'days',
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 3, // date: new Date(),
        active: false,
        achievement: 25,
        achievementCommentSuffix: 'replies',
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 3, // date: new Date(),
        active: false,
        achievement: 5,
        achievementCommentSuffix: 'tests',
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 4, // date: new Date(),
        active: false,
        achievement: 25,
        achievementCommentSuffix: 'days',
    },
    {
        id: undefined,
        title: 'Reply',
        type: 'comment',
        level: 4, // date: new Date(),
        active: false,
        achievement: 50,
        achievementCommentSuffix: 'replies',
    },
    {
        id: 'AIInImgrTirg5OAtf0sX',
        title: 'Test',
        type: 'test',
        level: 4, // date: new Date(),
        active: false,
        achievement: 8,
        achievementCommentSuffix: 'tests',
    },
    {
        id: undefined,
        title: 'Attend',
        type: 'attend',
        level: 5, // date: new Date(),
        active: false,
        achievement: 50,
        achievementCommentSuffix: 'days',
    },
    {
        id: 'ayvdW3j37hIZjBgJPeYu',
        title: 'Reply',
        type: 'comment',
        level: 5, // date: new Date(),
        active: false,
        achievement: 10,
        achievementCommentSuffix: 'replies',
    },
    {
        id: undefined,
        title: 'Test',
        type: 'test',
        level: 5, // date: new Date(),
        active: false,
        achievement: 100,
        achievementCommentSuffix: 'tests',
    },
];

export default badgeList;
